<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;

class VehicleController extends Controller
{
    // 1. This is your data source
    private function getVehicles() {
        return collect([
            1 => [
            'name' => 'Lexus RX Classic 350',
            'price' => 4890,
            'year' => '2007',
            'km' => '130,000 km',
            'fuel' => 'Essence',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-1.jpg',
            'desc' => '5-seater luxury SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors. Euro IV emission standard.',
        ],
            2 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-2.jpg',
            'desc' => '5-seater luxury SUV equipped with airbags, tire pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            3 => [
            'name' => 'Volkswagen Tiguan 1.8 TSI Automatique 4x4 Édition Fashion',
            'price' => 2750,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-3.jpg',
            'desc' => '5-seater luxury SUV equipped with airbags, tire pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            4 => [
            'name' => 'Suzuki Alto 1.0L Deluxe Edition',
            'price' => 1900,
            'year' => '2013',
            'km' => '100,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Purple',
            'trans' => 'Manual',
            'image' => 'Sinolink-4.jpg',
            'desc' => 'Hatchback equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchorages.',
        ],    
            5 => [
            'name' => 'Jetour X90 1.5T (5 seats)',
            'price' => 5300,
            'year' => '2019',
            'km' => '60,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Blue',
            'trans' => 'Automatic',
            'image' => 'Sinolink-5.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            6 => [
            'name' => 'Hyundai Tucson 1.6T',
            'price' => 7800,
            'year' => '2018',
            'km' => '87,200 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-6.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors. Condition: Water tank frame replaced, front right shock mount sheet metal repaired.',
        ],
            7 => [
            'name' => 'Land Rover Range Rover Evoque 2.0T',
            'price' => 7800,
            'year' => ' 2013',
            'km' => '115,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-7.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors. Included: Dynamic Panoramic Sunroof, Power Liftgate, Heated Seats, Multifunction Steering Wheel, Meridian Audio System, Permanent All-Wheel Drive and Keyless Start',
        ],
            8 => [
            'name' => 'Jeep Renegade (Freedom Man) 1.4T',
            'price' => 5600,
            'year' => '2017',
            'km' => '95,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-8.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            9 => [
            'name' => 'Jetour X70 Plus 1.6T (5 seats)',
            'price' => 11600,
            'year' => '2023',
            'km' => '57,712 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-9.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            10 => [
            'name' => 'Toyota Highlander 2.0T 4WD',
            'price' => 15600,
            'year' => '2016',
            'km' => '95,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-10.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors. Equipped with 360-degree panoramic imaging and four brand new tires.',
        ],
            11 => [
            'name' => 'Jetour Shan Hai T2 Mountain Edition',
            'price' => 21600,
            'year' => '2024',
            'km' => '208 km',
            'fuel' => 'Hybrid',
            'color' => 'Grey',
            'trans' => 'Automatic',
            'image' => 'Sinolink-11.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            12 => [
            'name' => 'Toyota Prado 2.7L 4WD (8 seats)',
            'price' => 7800,
            'year' => '2004',
            'km' => '310,990 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-12.jpg',
            'desc' => '8-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            13 => [
            'name' => 'Lexus RX350 3.5L 4WD',
            'price' => 5100,
            'year' => '2006',
            'km' => '180,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Grey',
            'trans' => 'Automatic',
            'image' => 'Sinolink-13.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            14 => [
            'name' => 'Toyota RAV4',
            'price' => 4300,
            'year' => '2009',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-14.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            15 => [
            'name' => 'Hyundai Verna 1.4L',
            'price' => 2700,
            'year' => '2011',
            'km' => '110,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Red',
            'trans' => 'Automatic',
            'image' => 'Sinolink-15.jpg',
            'desc' => 'Sedan equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            16 => [
            'name' => 'Hyundai Santa Fe 2.4Ln',
            'price' => 5800,
            'year' => '2014',
            'km' => '110,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Brown',
            'trans' => 'Automatic',
            'image' => 'Sinolink-16.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            17 => [
            'name' => 'Mercedes-Benz Vito',
            'price' => 19200,
            'year' => '2019',
            'km' => '70,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-17.jpg',
            'desc' => 'Commercial/family vehicle equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            18 => [
            'name' => 'Jeep Wrangler Sahara 3.8L',
            'price' => 9800,
            'year' => '2010',
            'km' => '120,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Orange',
            'trans' => 'Automatic',
            'image' => 'Sinolink-18.jpg',
            'desc' => 'Off-road SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            19 => [
            'name' => 'Jetour X70 PLUS (Powerful 1.6T version)',
            'price' => 12100,
            'year' => '2023',
            'km' => '26,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-19.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors. Original condition, first owner, no reported accidents.',
        ],
            20 => [
            'name' => 'Mercedes-Benz GLC Coupe (imported) GLC 260 4MATIC Coupe SUV',
            'price' => 28206,
            'year' => '2020',
            'km' => '68,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-20.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            21 => [
            'name' => 'Mercedes-Benz Classe CLA 220 4MATIC',
            'price' => 14024,
            'year' => '2018',
            'km' => '75,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Red',
            'trans' => 'Automatic',
            'image' => 'Sinolink-21.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            22 => [
            'name' => 'Changan UNI-T Flagship Edition 1.5T',
            'price' => 10,551,
            'year' => '2021',
            'km' => '25,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Dark Grey',
            'trans' => 'Automatic',
            'image' => 'Sinolink-22.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            23 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-23.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            24 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-24.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            25 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-25.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            26 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-26.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            27 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-27.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            28 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-28.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            29 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-29.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            30 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-30.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            31 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            32 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-32.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            33 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-33.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            34 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-34.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            35 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-35.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            36 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-36.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            37 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-37.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            38 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-38.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            39 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-39.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            40 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-40.jpg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            41 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-41.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            42 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-42.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            43 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-43.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            44 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-44.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            45 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-45.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            46 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-46.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            47 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-47.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            48 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-48.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            49 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-49.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            50 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-50.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            51 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-51.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            52 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-52.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            53 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-53.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            54 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-54.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            55 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-55.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            56 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-56.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            57 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-57.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            58 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-58.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            59 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-59.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            60 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-60.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
            61 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-61.jpeg',
            'desc' => 'Contact Sinolink Africa for full specifications and viewing arrangements for this vehicle.',
        ],
        
        
        ]);
    }

    // 2. This handles the Catalogue (20 per page)
   public function catalogue(Request $request)
    {
        $allVehicles = $this->getVehicles();
        $perPage = 20; 
        $currentPage = $request->input('page', 1);
        $currentItems = $allVehicles->slice(($currentPage - 1) * $perPage, $perPage)->all();

        $vehicles = new \Illuminate\Pagination\LengthAwarePaginator(
            $currentItems, 
            $allVehicles->count(), 
            $perPage, 
            $currentPage, 
            ['path' => $request->url(), 'query' => $request->query()]
        );

        // ADD THIS LINE: It passes the $vehicles variable to your blade
        return view('catalogue', compact('vehicles'));
    }

    // 3. PLACE THE NEW CODE HERE (Handles the specific car page)
    public function show($id)
    {
        $allVehicles = $this->getVehicles();
        
        if (!isset($allVehicles[$id])) {
            abort(404);
        }

        $vehicle = $allVehicles[$id];

        return view('vehicle-details', compact('vehicle'));
    }
}
