<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;

class VehicleController extends Controller
{
    // 1. This is your data source
    private function getVehicles() {
        return collect([
            1 => [
            'name' => 'Lexus RX Classic 350',
            'slug' => 'Lexus-RX-Classic-350',
            'price' => 4890,
            'year' => '2007',
            'km' => '130,000 km',
            'fuel' => 'Essence',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-1.jpg',
            'desc' => '5-seater luxury SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors. Euro IV emission standard.',
        ],
            2 => [
            'name' => 'Audi Q5 2.0 TFSI Technology Edition',
            'slug' => 'Audi-Q5-2.0-TFSI-Technology-Edition',
            'price' => 4300,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-2.jpg',
            'desc' => '5-seater luxury SUV equipped with airbags, tire pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            3 => [
            'name' => 'Volkswagen Tiguan 1.8 TSI Automatique 4x4 Édition Fashion',
            'slug' => 'Volkswagen-Tiguan-1.8-TSI-Automatique-4x4-Édition-Fashion',
            'price' => 2750,
            'year' => '2010',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-3.jpg',
            'desc' => '5-seater luxury SUV equipped with airbags, tire pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            4 => [
            'name' => 'Suzuki Alto 1.0L Deluxe Edition',
            'slug' => 'Suzuki-Alto-1.0L-Deluxe-Edition',
            'price' => 1900,
            'year' => '2013',
            'km' => '100,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Purple',
            'trans' => 'Manual',
            'image' => 'Sinolink-4.jpg',
            'desc' => 'Hatchback equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchorages.',
        ],    
            5 => [
            'name' => 'Jetour X90 1.5T (5 seats)',
            'slug' => 'Jetour-X90-1.5T-(5-seats)',
            'price' => 5300,
            'year' => '2019',
            'km' => '60,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Blue',
            'trans' => 'Automatic',
            'image' => 'Sinolink-5.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            6 => [
            'name' => 'Hyundai Tucson 1.6T',
            'slug' => 'Hyundai-Tucson-1.6T',
            'price' => 7800,
            'year' => '2018',
            'km' => '87,200 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-6.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors. Condition: Water tank frame replaced, front right shock mount sheet metal repaired.',
        ],
            7 => [
            'name' => 'Land Rover Range Rover Evoque 2.0T',
            'slug' => 'Land-Rover-Range-Rover-Evoque-2.0T',
            'price' => 7800,
            'year' => ' 2013',
            'km' => '115,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-7.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors. Included: Dynamic Panoramic Sunroof, Power Liftgate, Heated Seats, Multifunction Steering Wheel, Meridian Audio System, Permanent All-Wheel Drive and Keyless Start',
        ],
            8 => [
            'name' => 'Jeep Renegade (Freedom Man) 1.4T',
            'slug' => 'Jeep-Renegade-(Freedom-Man)-1.4T',
            'price' => 5600,
            'year' => '2017',
            'km' => '95,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-8.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            9 => [
            'name' => 'Jetour X70 Plus 1.6T (5 seats)',
            'slug' => 'Jetour-X70-Plus-1.6T-(5-seats)',
            'price' => 11600,
            'year' => '2023',
            'km' => '57,712 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-9.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            10 => [
            'name' => 'Toyota Highlander 2.0T 4WD',
            'slug' => 'Toyota-Highlander-2.0T-4WD',
            'price' => 15600,
            'year' => '2016',
            'km' => '95,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-10.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors. Equipped with 360-degree panoramic imaging and four brand new tires.',
        ],
            11 => [
            'name' => 'Jetour Shan Hai T2 Mountain Edition',
            'slug' => 'Jetour-Shan-Hai-T2-Mountain-Edition',
            'price' => 21600,
            'year' => '2024',
            'km' => '208 km',
            'fuel' => 'Hybrid',
            'color' => 'Grey',
            'trans' => 'Automatic',
            'image' => 'Sinolink-11.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            12 => [
            'name' => 'Toyota Prado 2.7L 4WD (8 seats)',
            'slug' => 'Toyota-Prado-2.7L-4WD-(8-seats)',
            'price' => 7800,
            'year' => '2004',
            'km' => '310,990 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-12.jpg',
            'desc' => '8-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            13 => [
            'name' => 'Lexus RX350 3.5L 4WD',
            'slug' => 'Lexus-RX350-3.5L-4WD',
            'price' => 5100,
            'year' => '2006',
            'km' => '180,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Grey',
            'trans' => 'Automatic',
            'image' => 'Sinolink-13.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            14 => [
            'name' => 'Toyota RAV4',
            'slug' => 'Toyota-RAV4',
            'price' => 4300,
            'year' => '2009',
            'km' => '125,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-14.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            15 => [
            'name' => 'Hyundai Verna 1.4L',
            'slug' => 'Hyundai-Verna-1.4L',
            'price' => 2700,
            'year' => '2011',
            'km' => '110,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Red',
            'trans' => 'Automatic',
            'image' => 'Sinolink-15.jpg',
            'desc' => 'Sedan equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            16 => [
            'name' => 'Hyundai Santa Fe 2.4Ln',
            'price' => 5800,
            'year' => '2014',
            'km' => '110,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Brown',
            'trans' => 'Automatic',
            'image' => 'Sinolink-16.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            17 => [
            'name' => 'Mercedes-Benz Vito',
            'slug' => 'Mercedes-Benz-Vito',
            'price' => 19200,
            'year' => '2019',
            'km' => '70,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-17.jpg',
            'desc' => 'Commercial/family vehicle equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            18 => [
            'name' => 'Jeep Wrangler Sahara 3.8L',
            'slug' => 'Jeep-Wrangler-Sahara-3.8L',
            'price' => 9800,
            'year' => '2010',
            'km' => '120,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Orange',
            'trans' => 'Automatic',
            'image' => 'Sinolink-18.jpg',
            'desc' => 'Off-road SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            19 => [
            'name' => 'Jetour X70 PLUS (Powerful 1.6T version)',
            'slug' => 'Jetour-X70-PLUS-(Powerful-1.6T-version)',
            'price' => 12100,
            'year' => '2023',
            'km' => '26,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-19.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors. Original condition, first owner, no reported accidents.',
        ],
            20 => [
            'name' => 'Mercedes-Benz GLC Coupe (imported) GLC 260 4MATIC Coupe SUV',
            'slug' => 'Mercedes-Benz-GLC-Coupe-(imported)-GLC-260-4MATIC-Coupe-SUV',
            'price' => 28206,
            'year' => '2020',
            'km' => '68,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-20.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            21 => [
            'name' => 'Mercedes-Benz Classe CLA 220 4MATIC',
            'slug' => 'Mercedes-Benz-Classe-CLA-220-4MATIC',
            'price' => 14024,
            'year' => '2018',
            'km' => '75,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Red',
            'trans' => 'Automatic',
            'image' => 'Sinolink-21.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            22 => [
            'name' => 'Changan UNI-T Flagship Edition 1.5T',
            'slug' => 'Changan-UNI-T-Flagship-Edition-1.5T',
            'price' => 10551,
            'year' => '2021',
            'km' => '25,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Dark Grey',
            'trans' => 'Automatic',
            'image' => 'Sinolink-22.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            23 => [
            'name' => 'Jetour X70 PLUS 1.6T DCT 5 seater',
            'slug' => 'Jetour-X70-PLUS-1.6T-DCT-5-seater',
            'price' => 10136,
            'year' => '2021',
            'km' => '40,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Blue',
            'trans' => 'Automatic',
            'image' => 'Sinolink-23.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors',
        ],
            24 => [
            'name' => 'Mazda CX-5 Cloud Control Edition 2.0L Automatic 2WD Smart Model',
            'slug' => 'Mazda-CX-5-Cloud-Control-Edition-2.0L-Automatic-2WD-Smart-Model',
            'price' => 9859,
            'year' => '2019',
            'km' => '50,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-24.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            25 => [
            'name' => 'Jetour X70 PLUS 1.5T DCT MTB PRO 5 seater',
            'slug' => 'Jetour-X70-PLUS-1.5T-DCT-MTB-PRO-5-seater',
            'price' => 9581,
            'year' => '2021',
            'km' => '51,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-25.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors',
        ],
            26 => [
            'name' => 'Kia Sportage 2.0L Automatic Smart Luxury Edition',
            'slug' => 'Kia-Sportage-2.0L-Automatic-Smart-Luxury-Edition',
            'price' => 9165,
            'year' => '2019',
            'km' => '50,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-26.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            27 => [
            'name' => 'Toyota Prado (Imported) GX 2700 Class Automatic',
            'slug' => 'Toyota-Prado-(Imported)-GX-2700-Class-Automatic',
            'price' => 8902,
            'year' => '2007',
            'km' => '290,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Silver Grey',
            'trans' => 'Automatic',
            'image' => 'Sinolink-27.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            28 => [
            'name' => 'Changan CS55 PLUS Whale Edition',
            'slug' => 'Changan-CS55-PLUS-Whale-Edition',
            'price' => 8749,
            'year' => '2021',
            'km' => '40,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Dark Grey',
            'trans' => 'Automatic',
            'image' => 'Sinolink-28.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            29 => [
            'name' => 'Toyota IZOA 2.0L Aeolus Edition',
            'slug' => 'Toyota-IZOA-2.0L-Aeolus-Edition',
            'price' => 8749,
            'year' => '2019',
            'km' => '66,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Red',
            'trans' => 'Automatic',
            'image' => 'Sinolink-29.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            30 => [
            'name' => 'Changan Oushang X5 1.5T DCT Flagship Edition',
            'slug' => 'Changan-Oushang-X5-1.5T-DCT-Flagship-Edition',
            'price' => 8472,
            'year' => '2021',
            'km' => '27,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Red',
            'trans' => 'Automatic',
            'image' => 'Sinolink-30.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            31 => [
            'name' => 'Toyota Reiz 2.5V Premium Edition',
            'slug' => 'Toyota Reiz 2.5V Premium Edition',
            'price' => 8472,
            'year' => '2014',
            'km' => '160,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Blue',
            'trans' => 'Automatic',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            32 => [
            'name' => 'Toyota RAV4 2.0L CVT 2WD Urban Edition',
            'slug' => 'Toyota-RAV4-2.0L-CVT-2WD-Urban-Edition',
            'price' => 6498,
            'year' => '2014',
            'km' => '85,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Red',
            'trans' => 'Automatic',
            'image' => 'Sinolink-32.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            33 => [
            'name' => 'Kia KX5 1.6T Automatic 2WD Premium',
            'slug' => 'Kia-KX5-1.6T-Automatic-2WD-Premium',
            'price' => 7087,
            'year' => '2016',
            'km' => '30,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-33.jpg',
            'desc' => '5-seater SUV equipped with airbags (driver/passenger, side and curtain), tyre pressure monitoring, ISOFIX anchorages, ABS and keyless ignition system.',
        ],
            34 => [
            'name' => 'Toyota RAV4 2.0L CVT 2WD Urban Edition',
            'slug' => 'Toyota-RAV4-2.0L-CVT-2WD-Urban-Edition',
            'price' => 6671,
            'year' => '2013',
            'km' => '94,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Orange',
            'trans' => 'Automatic',
            'image' => 'Sinolink-34.jpg',
            'desc' => '5-seater SUV equipped with airbags (driver/passenger, side and curtain), ISOFIX anchorages, ABS and electronic brake-force distribution (EBD).',
        ],
            35 => [
            'name' => 'Kia Sportage 2.0L Automatic 2WD GL',
            'slug' => 'Kia-Sportage-2.0L-Automatic-2WD-GL',
            'price' => 6352,
            'year' => '2017',
            'km' => '6,532 km',
            'fuel' => 'Gasoline',
            'color' => 'Brown',
            'trans' => 'Automatic',
            'image' => 'Sinolink-35.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            36 => [
            'name' => 'Hyundai Tucson 1.6T dual-clutch and two-wheel drive',
            'slug' => 'Hyundai-Tucson-1.6T-dual-clutch-and-two-wheel-drive',
            'price' => 6352,
            'year' => '2016',
            'km' => '90,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Brown',
            'trans' => 'Automatic',
            'image' => 'Sinolink-36.jpg',
            'desc' => '5-seater SUV equipped with a 1.6T turbo engine, including airbags (driver/passenger, side and curtain), ISOFIX anchorages, as well as keyless ignition systems, ABS and EBD.',
        ],
            37 => [
            'name' => 'Hyundai Tucson 1.6T dual-clutch and two-wheel drive',
            'slug' => 'Hyundai-Tucson-1.6T-dual-clutch-and-two-wheel-drive',
            'price' => 6394,
            'year' => '2016',
            'km' => '76,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Brown',
            'trans' => 'Automatic',
            'image' => 'Sinolink-37.jpg',
            'desc' => '5-seater SUV with a 1.6T turbocharged engine, including airbags (driver/passenger, side and curtain), ISOFIX anchorages, as well as keyless ignition systems, ABS and EBD.',
        ],
            38 => [
            'name' => 'Kia Sportage 2.0L Automatic 2WD DLX',
            'slug' => 'Kia-Sportage-2.0L-Automatic-2WD-DLX',
            'price' => 5978,
            'year' => '2016',
            'km' => '100,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-38.jpg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            39 => [
            'name' => 'Hyundai Tucson 1.6T dual-clutch and two-wheel drive',
            'slug' => 'Hyundai-Tucson-1.6T-dual-clutch-and-two-wheel-drive',
            'price' => 5978,
            'year' => '2015',
            'km' => '133,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-39.jpg',
            'desc' => '5-seater SUV equipped with a 1.6T turbo engine, including airbags (driver/passenger, side and curtain), ISOFIX anchors, as well as ABS and EBD systems.',
        ],
            40 => [
            'name' => 'Geely Binyue',
            'slug' => 'Geely-Binyue',
            'price' => 5978,
            'year' => '2019',
            'km' => '50,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-40.jpg',
            'desc' => '5-seater SUV equipped with a 1.5T turbo engine, including airbags (driver/passenger, side and curtain), tire pressure monitoring, ISOFIX anchors and keyless ignition system.',
        ],
            41 => [
            'name' => '2009 Toyota Highlander 2.7L 2WD 5-passenger Elite Edition',
            'slug' => '2009-Toyota- Highlander-2.7L-2WD-5-passenger-Elite-Edition',
            'price' => 5146,
            'year' => '2008',
            'km' => '200,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-41.jpeg',
            'desc' => '5-seater SUV equipped with airbags (driver/passenger, side, curtain and knee), ISOFIX anchorages, ABS, EBD and vehicle stability control.',
        ],
            42 => [
            'name' => 'Toyota Yaris 1.3E Comfort Edition',
            'slug' => 'Toyota-Yaris-1.3E-Comfort-Edition',
            'price' => 2915,
            'year' => '2008',
            'km' => '99,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Purple',
            'trans' => 'Automatic',
            'image' => 'Sinolink-42.jpeg',
            'desc' => '5-seater hatchback model, 1.3L engine. Equipped with ABS/EBD brakes, ISOFIX anchors and double airbags. Euro IV emission standard.',
        ],
            43 => [
            'name' => 'Zotye SR7 2016 1.5T CVT Magic Cube Edition',
            'slug' => 'Zotye-SR7-2016-1.5T-CVT-Magic-Cube-Edition',
            'price' => 2915,
            'year' => '2017',
            'km' => '61,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Brown',
            'trans' => 'Automatic',
            'image' => 'Sinolink-43.jpeg',
            'desc' => '5-seater SUV equipped with a turbo engine. It has the keyless entry and start-up system, airbags and ISOFIX anchorages for child seats. This model complies with the national emission standard V.',
        ],
            44 => [
            'name' => 'Zotye SR7 2016 1.5T CVT Magic Cube Edition',
            'slug' => 'Zotye-SR7-2016-1.5T-CVT-Magic-Cube-Edition',
            'price' => 3151,
            'year' => '2016',
            'km' => '105,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Brown',
            'trans' => 'Manual',
            'image' => 'Sinolink-44.jpeg',
            'desc' => '5-seater SUV equipped with a turbo engine. It has the keyless entry and start-up system, airbags and ISOFIX anchorages for child seats. This model complies with the national emission standard V.',
        ],
            45 => [
            'name' => 'Honda Fit 1.5L manual',
            'slug' => 'Honda-Fit-1.5L-manual',
            'price' => 3085,
            'year' => '2005',
            'km' => '180,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Silver Grey',
            'trans' => 'Manual',
            'image' => 'Sinolink-44.jpeg',
            'desc' => '5-seater front-wheel drive hatchback model. Equipped with driver/passenger airbags, ABS braking system and electronic brake-force distribution (EBD). Complies with the Euro IV emission standard.',
        ],
            46 => [
            'name' => 'BAIC Huansu S5 2017 1.3T CVT Luxury Edition',
            'slug' => 'BAIC-Huansu-S5-2017-1.3T-CVT-Luxury-Edition',
            'price' => 3203,
            'year' => '2015',
            'km' => '50,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Red',
            'trans' => 'Automatic',
            'image' => 'Sinolink-46.jpeg',
            'desc' => '5-seater front-wheel drive SUV, equipped with a turbo engine. The vehicle has driver, passenger and side airbags (front/rear), a tyre pressure monitoring system and ISOFIX anchorages.',
        ],
            47 => [
            'name' => '2004 Toyota Corolla 1.8L Automatic GL-i',
            'slug' => '2004-Toyota-Corolla-1.8L-Automatic-GL-i',
            'price' => 3294,
            'year' => '2006',
            'km' => '250,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Silver Grey',
            'trans' => 'Automatic',
            'image' => 'Sinolink-47.jpeg',
            'desc' => '5-seater sedan with front-wheel drive. It is equipped with driver/passenger airbags, the ABS braking system, electronic brake-force distribution (EBD) and front/rear electric windows. This model meets the Euro 3 emission standard.',
        ],
            48 => [
            'name' => 'Haval H6 2016 Improved Version 1.5T Manual 2WD Elite',
            'slug' => 'Haval-H6-2016-Improved-Version-1.5T-Manual-2WD-Elite',
            'price' => 3203,
            'year' => '2016',
            'km' => '100,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Manual',
            'image' => 'Sinolink-48.jpeg',
            'desc' => '5-seater SUV with front-wheel drive, equipped with airbags, tyre pressure monitoring, ISOFIX anchors and keyless start.',
        ],
            49 => [
            'name' => 'Zotye R7 2017 1.5T CVT Magic Cube Edition',
            'slug' => 'Zotye-R7-2017-1.5T-CVT-Magic-Cube-Edition',
            'price' => 3203,
            'year' => '2016',
            'km' => '100,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-49.jpeg',
            'desc' => '5-seater SUV with front-wheel drive. Equipped with airbags, ISOFIX ANCHORS, ABS/EBD, hill start assist, automatic parking and roof racks.',
        ],
            50 => [
            'name' => '2011 Toyota Corolla 1.6L Manual GL',
            'slug' => '2011-Toyota-Corolla-1.6L-Manual-GL',
            'price' => 3342,
            'year' => '2011',
            'km' => '134,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Manual',
            'image' => 'Sinolink-50.jpeg',
            'desc' => '5-seater sedan with front-wheel drive. Equipped with driver/passenger airbags, ISOFIX anchorages, ABS braking system and electronic brake-force distribution (EBD).',
        ],
            51 => [
            'name' => '2013 Volkswagen Santana 1.6L Automatic Edition Mode',
            'slug' => '2013-Volkswagen-Santana-1.6L-Automatic-Edition-Mode',
            'price' => 3342,
            'year' => '2014',
            'km' => '133,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-51.jpeg',
            'desc' => '5-seater sedan with front-wheel drive. Equipped with driver/passenger and side (front/rear) airbags, ISOFIX anchorages for child seats and an ABS anti-lock braking system.',
        ],
            52 => [
            'name' => 'Zotye SR7 2017 1.5T CVT Magic Cube Dream Edition',
            'slug' => 'Zotye-SR7-2017-1.5T-CVT-Magic-Cube-Dream-Edition',
            'price' => 3481,
            'year' => '2017',
            'km' => '95,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Brown',
            'trans' => 'Automatic',
            'image' => 'Sinolink-52.jpeg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            53 => [
            'name' => 'Cheetah CS10 2017 2.0T Automatic Leader Edition',
            'slug' => 'Cheetah-CS10-2017-2.0T-Automatic-Leader-Edition',
            'price' => 3481,
            'year' => '2017',
            'km' => '91,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-53.jpeg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            54 => [
            'name' => 'Zotye SR7 2017 1.5T CVT Magic Cube Dream Edition',
            'slug' => 'Zotye-SR7-2017-1.5T-CVT-Magic-Cube-Dream-Edition',
            'price' => 3481,
            'year' => '2017',
            'km' => '120,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-54.jpeg',
            'desc' => '5-seater SUV equipped with airbags (driver/passenger and side), tyre pressure monitoring, ISOFIX anchors, keyless start/entry and ABS/EBD system.',
        ],
            55 => [
            'name' => 'Hyundai ix35 2012 2.0L Automatic 2WD Elite Edition GL (Beijing)',
            'slug' => 'Hyundai ix35 2012 2.0L Automatic 2WD Elite Edition GL (Beijing)',
            'price' => 4034,
            'year' => '2013',
            'km' => '80,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-55.jpeg',
            'desc' => '5-seater front-wheel drive SUV, equipped with airbags, ISOFIX anchorages, ABS braking system and electronic brake-force distribution (EBD).',
        ],
            56 => [
            'name' => 'Geely Emgrand GS 2016 Sport Edition 1.3T Automatic Premium',
            'slug' => 'Geely-Emgrand-GS-2016-Sport-Edition-1.3T-Automatic-Premium',
            'price' => 4172,
            'year' => '2016',
            'km' => '64,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Blue',
            'trans' => 'Automatic',
            'image' => 'Sinolink-56.jpeg',
            'desc' => '5-seater SUV equipped with a turbo engine. It has airbags (driver, passenger, side and front/rear curtains), a tyre pressure monitoring system and ISOFIX anchorages.',
        ],
            57 => [
            'name' => '2012 Kia Sorento 2.4L Petrol Luxury Edition',
            'slug' => '2012-Kia-Sorento-2.4L-Petrol-Luxury-Edition',
            'price' => 4311,
            'year' => '2012',
            'km' => '60,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Brown',
            'trans' => 'Automatic',
            'image' => 'Sinolink-57.jpeg',
            'desc' => '5-seater SUV with front-wheel drive, equipped with airbags, keyless entry and entry system, ABS, EBD, stability control, panoramic sunroof and multifunction steering wheel.',
        ],
            58 => [
            'name' => 'Beijing Hyundai ix35 2013 2.0L Automatic 2WD Smart GLS',
            'slug' => 'Beijing-Hyundai-ix35-2013-2.0L-Automatic-2WD-Smart-GLS',
            'price' => 4311,
            'year' => '2013',
            'km' => '88,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Black',
            'trans' => 'Automatic',
            'image' => 'Sinolink-58.jpeg',
            'desc' => '5-seater SUV equipped with airbags, tyre pressure monitoring, ISOFIX, ABS and EBD anchors.',
        ],
            59 => [
            'name' => 'Hyundai ix35 2012 2.0L Automatic 2WD Elite GLS (Beijing)',
            'slug' => 'Hyundai-ix35-2012-2.0L-Automatic-2WD-Elite-GLS-(Beijing)',
            'price' => 4451,
            'year' => '2012',
            'km' => '110,000 km',
            'fuel' => 'Gasoline',
            'color' => 'White',
            'trans' => 'Automatic',
            'image' => 'Sinolink-59.jpeg',
            'desc' => '5-seater front-wheel drive SUV, equipped with driver/passenger and front/rear side airbags, ISOFIX anchors and a keyless ignition system.',
        ],
            60 => [
            'name' => '2009 Toyota RAV4 2.0L Automatic Deluxe Edition',
            'slug' => '2009-Toyota-RAV4-2.0L-Automatic-Deluxe-Edition',
            'price' => 4590,
            'year' => '2010',
            'km' => '128,000 km',
            'fuel' => 'Hybrid',
            'color' => 'Grey',
            'trans' => 'Automatic',
            'image' => 'Sinolink-60.jpeg',
            'desc' => '5-seater SUV with front-wheel drive. Equipped with airbags (driver/passenger, side and front/rear curtains), ISOFIX anchorages, ABS/EBD system and hill start assist.',
        ],
            61 => [
            'name' => '2009 Toyota Reiz 2.5S Comfort Edition',
            'slug' => '2009-Toyota-Reiz-2.5S-Comfort-Edition',
            'price' => 4590,
            'year' => '2009',
            'km' => '210,000 km',
            'fuel' => 'Gasoline',
            'color' => 'Grey',
            'trans' => 'Automatic',
            'image' => 'Sinolink-61.jpeg',
            'desc' => '5-seater rear-wheel drive sedan, equipped with driver/passenger and side airbags, ISOFIX anchors, ABS and electronic brake-force distribution (EBD).',
        ],
        
        
        ]);
    }

    // 2. This handles the Catalogue (20 per page)
   public function catalogue(Request $request)
{
    // 1. Get all vehicles as a Collection so we can filter easily
    $allVehicles = collect($this->getVehicles());

    // 2. APPLY FILTERS
    // Search by name
    if ($request->filled('search')) {
        $search = strtolower($request->search);
        $allVehicles = $allVehicles->filter(function($item) use ($search) {
            return str_contains(strtolower($item['name']), $search);
        });
    }

    // Filter by Brand
    if ($request->filled('brand')) {
        $brand = $request->brand; // No strtolower here if your array values are capitalized
        $allVehicles = $allVehicles->filter(function($item) use ($brand) {
            // Check for an explicit 'brand' key, or if the name starts with the brand
            return (isset($item['brand']) && $item['brand'] === $brand) || 
                   str_starts_with($item['name'], $brand);
        });
    }
    // Filter by Price
    if ($request->filled('min_price')) {
        $allVehicles = $allVehicles->where('price', '>=', $request->min_price);
    }
    if ($request->filled('max_price')) {
        $allVehicles = $allVehicles->where('price', '<=', $request->max_price);
    }

    // 3. APPLY SORTING
    if ($request->filled('sort')) {
    switch ($request->sort) {
        case 'price_asc':
            $allVehicles = $allVehicles->sortBy('price');
            break;
        case 'price_desc':
            $allVehicles = $allVehicles->sortByDesc('price');
            break;
        case 'year_new':
            $allVehicles = $allVehicles->sortByDesc('year');
            break;
        case 'year_old':
            $allVehicles = $allVehicles->sortBy('year');
            break;
    }
}


    // 4. PAGINATION (Uses the filtered/sorted collection)
    $perPage = 20; 
    $currentPage = $request->input('page', 1);
    
    // Slice the filtered collection
    $currentItems = $allVehicles->slice(($currentPage - 1) * $perPage, $perPage)->all();

    $vehicles = new \Illuminate\Pagination\LengthAwarePaginator(
        $currentItems, 
        $allVehicles->count(), 
        $perPage, 
        $currentPage, 
        ['path' => $request->url(), 'query' => $request->query()]
    );

    return view('catalogue', compact('vehicles'));
}
    public function show($slug, \Illuminate\Http\Request $request)
    {
        // 1. If the URL has ?ref=AGENT01, save "AGENT01" to the browser session
        if ($request->has('ref')) {
            session(['referrer' => $request->query('ref')]);
        }

        $vehicles = $this->getVehicles();
        
        // 2. Finding the car using the slug
        $vehicle = $vehicles->firstWhere('slug', $slug);

        if (!$vehicle) {
            abort(404);
        }

        return view('vehicle-details', compact('vehicle'));
}

}

            
